import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

type JsPDFWithAutoTable = jsPDF & {
  lastAutoTable?: {
    finalY: number
  }
}

export interface InvoiceItem {
  description: string
  sku?: string
  quantity: number
  unitPrice: number
  totalPrice: number
}

export interface InvoiceData {
  invoiceNumber: string

  type:'PURCHASE' | 'SALE'

  issuedAt: string

  companyName: string
  companyAddress: string
  companyPhone: string
  companyEmail: string

  supplierName: string

  items: InvoiceItem[]

  subtotal: number

  totalAmount: number

  status: string

  notes?: string
}

export function generatePurchaseInvoice(data: InvoiceData) {

  const doc = new jsPDF()

  const pageWidth = doc.internal.pageSize.getWidth()

  //---------------------------------------------------------
  // HEADER
  //---------------------------------------------------------

  doc.setFillColor(16,185,129)
  doc.rect(0,0,pageWidth,35,'F')

  doc.setTextColor(255,255,255)

  doc.setFontSize(24)

  doc.setFont('helvetica','bold')

  doc.text(data.companyName,15,15)

  doc.setFontSize(10)

  doc.setFont('helvetica','normal')

  doc.text(data.companyAddress,15,22)

  doc.text(data.companyPhone,15,27)

  doc.text(data.companyEmail,15,32)

  //---------------------------------------------------------

  doc.setTextColor(30,30,30)

  doc.setFontSize(20)

  doc.setFont('helvetica','bold')

  doc.text(
data.type === 'SALE'
  ? 'SALES INVOICE'
  : 'PURCHASE ORDER',140,20)

  doc.setFontSize(10)

  doc.setFont('helvetica','normal')

  doc.text(`Invoice : ${data.invoiceNumber}`,140,28)

  doc.text(`Date : ${new Date(data.issuedAt).toLocaleDateString()}`,140,34)

  //---------------------------------------------------------
  // Supplier
  //---------------------------------------------------------

  doc.setFont('helvetica','bold')

  doc.setFontSize(12)

  doc.text('Supplier',15,48)

  doc.setFont('helvetica','normal')

  doc.setFontSize(11)

  doc.text(data.supplierName,15,56)

  //---------------------------------------------------------
  // STATUS
  //---------------------------------------------------------

  doc.setFillColor(16,185,129)

  doc.roundedRect(155,44,40,10,2,2,'F')

  doc.setTextColor(255,255,255)

  doc.setFontSize(9)

  doc.setFont('helvetica','bold')

  doc.text(
    data.status.toUpperCase(),
    175,
    50,
    { align:'center' }
  )

  //---------------------------------------------------------
  // TABLE
  //---------------------------------------------------------

  autoTable(doc,{

    startY:70,

    head:[[
      '#',
      'Product',
      'SKU',
      'Qty',
      'Unit Cost',
      'Subtotal'
    ]],

    body:data.items.map((item,index)=>[

      index+1,

      item.description,

      item.sku ?? '-',

      item.quantity,

      `Rs ${item.unitPrice.toLocaleString()}`,

      `Rs ${item.totalPrice.toLocaleString()}`
    ]),

    theme:'striped',

    headStyles:{
      fillColor:[16,185,129]
    }

  })

  //---------------------------------------------------------

  const y =
  ((doc as JsPDFWithAutoTable).lastAutoTable?.finalY ?? 70) + 12

  doc.setFont('helvetica','bold')

  doc.setFontSize(12)

  doc.text(
    `Grand Total : Rs ${Math.round(data.totalAmount).toLocaleString()}`,
    135,
    y
  )

  if(data.notes){

    doc.setFont('helvetica','bold')

    doc.text('Notes',15,y)

    doc.setFont('helvetica','normal')

    doc.text(data.notes,15,y+8)

  }

  //---------------------------------------------------------
  // FOOTER
  //---------------------------------------------------------

  const pageHeight=doc.internal.pageSize.getHeight()

  doc.setDrawColor(220)

  doc.line(
    15,
    pageHeight-20,
    pageWidth-15,
    pageHeight-20
  )

  doc.setFontSize(9)

  doc.setTextColor(100)

  doc.text(
    'Generated by StockFlow Inventory Management System',
    pageWidth/2,
    pageHeight-12,
    { align:'center' }
  )

  return doc

}

export function downloadPurchaseInvoice(data:InvoiceData){

  const doc=generatePurchaseInvoice(data)

  doc.save(`${data.invoiceNumber}.pdf`)

}

export function printPurchaseInvoice(data:InvoiceData){

  const doc=generatePurchaseInvoice(data)

  const blob=doc.output('blob')

  const url=URL.createObjectURL(blob)

  const win=window.open(url)

  win?.addEventListener('load',()=>{

    win.print()

    URL.revokeObjectURL(url)

  })

}